### ISSUE TITLE
unable to "use"

### ISSUE THREAD

**Issue by OwnageGalore** [jonassvensson4/jsfour-licenseplate#1]
i have it in game, but when i go to use the item im unable to. so no menu pops up for it or anything.

**Comment by jnsvns** [comment]
Can't really help you if there are no errors. 

Should work unless you're using some other inventory than the default one from ESX, they might handle the usable items differently.

**Comment by OwnageGalore** [comment]
thats probably it, i use the esx_inventoryhud system. lets see if i can pull my hair out to try and figure this out
